"""Add OneDrive models

Revision ID: 3f1d495bf47b
Revises: 658cba26ab64
Create Date: 2026-09-29 15:21:44.635419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1d495bf47b'
down_revision: Union[str, None] = '658cba26ab64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onedrive_delta_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=255), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onedrive_delta_account_drive', 'onedrive_delta_links', ['account_id', 'drive_id'], unique=True)
    op.create_index(op.f('ix_onedrive_delta_links_account_id'), 'onedrive_delta_links', ['account_id'], unique=False)
    op.create_table('onedrive_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('last_modified_by_id', sa.String(length=255), nullable=True),
    sa.Column('last_modified_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at_local', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['onedrive_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onedrive_files_account_id'), 'onedrive_files', ['account_id'], unique=False)
    op.create_index('ix_onedrive_files_account_parent', 'onedrive_files', ['account_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_onedrive_files_content_hash'), 'onedrive_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_onedrive_files_created_at'), 'onedrive_files', ['created_at'], unique=False)
    op.create_index('ix_onedrive_files_graph_id', 'onedrive_files', ['graph_id'], unique=True)
    op.create_index('ix_onedrive_files_last_modified', 'onedrive_files', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_onedrive_files_last_modified_at'), 'onedrive_files', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_onedrive_files_parent_id'), 'onedrive_files', ['parent_id'], unique=False)
    op.drop_index('ix_emails_graph_id', table_name='emails')
    op.create_index(op.f('ix_emails_graph_id'), 'emails', ['graph_id'], unique=False)
    op.drop_index('ix_teams_chats_graph_id', table_name='teams_chats')
    op.create_index(op.f('ix_teams_chats_graph_id'), 'teams_chats', ['graph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_chats_graph_id'), table_name='teams_chats')
    op.create_index('ix_teams_chats_graph_id', 'teams_chats', ['graph_id'], unique=1)
    op.drop_index(op.f('ix_emails_graph_id'), table_name='emails')
    op.create_index('ix_emails_graph_id', 'emails', ['graph_id'], unique=1)
    op.drop_index(op.f('ix_onedrive_files_parent_id'), table_name='onedrive_files')
    op.drop_index(op.f('ix_onedrive_files_last_modified_at'), table_name='onedrive_files')
    op.drop_index('ix_onedrive_files_last_modified', table_name='onedrive_files')
    op.drop_index('ix_onedrive_files_graph_id', table_name='onedrive_files')
    op.drop_index(op.f('ix_onedrive_files_created_at'), table_name='onedrive_files')
    op.drop_index(op.f('ix_onedrive_files_content_hash'), table_name='onedrive_files')
    op.drop_index('ix_onedrive_files_account_parent', table_name='onedrive_files')
    op.drop_index(op.f('ix_onedrive_files_account_id'), table_name='onedrive_files')
    op.drop_table('onedrive_files')
    op.drop_index(op.f('ix_onedrive_delta_links_account_id'), table_name='onedrive_delta_links')
    op.drop_index('ix_onedrive_delta_account_drive', table_name='onedrive_delta_links')
    op.drop_table('onedrive_delta_links')
    # ### end Alembic commands ###