"""Initial migration

Revision ID: 464f02899512
Revises: 
Create Date: 2026-09-29 11:46:43.850700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464f02899512'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'ERROR', 'DISCONNECTED', name='accountstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_provider_account', 'accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_index(op.f('ix_accounts_provider_account_id'), 'accounts', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_index('ix_accounts_user_provider', 'accounts', ['user_id', 'provider'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_user_id'), 'embeddings', ['user_id'], unique=False)
    op.create_index('ix_embeddings_user_vector', 'embeddings', ['user_id', 'vector_id'], unique=True)
    op.create_index(op.f('ix_embeddings_vector_id'), 'embeddings', ['vector_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_logs_correlation', 'event_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_logs_correlation_id'), 'event_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index('ix_event_logs_type_created', 'event_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DEADLINE_APPROACHING', 'MEETING_APPROACHING', 'FOLLOWUP_DUE', 'TASK_BLOCKED', 'NEW_TASK_DETECTED', 'COMMITMENT_DUE', 'DAILY_BRIEFING', 'END_OF_DAY', 'SYNC_COMPLETED', 'SYNC_FAILED', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'REMINDER', 'IMPORTANT', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('detected_automatically', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=False)
    op.create_index('ix_settings_user_key', 'settings', ['user_id', 'key'], unique=True)
    op.create_table('ai_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['embeddings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memory_embedding_id'), 'ai_memory', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_ai_memory_user_id'), 'ai_memory', ['user_id'], unique=False)
    op.create_index('ix_ai_memory_user_source', 'ai_memory', ['user_id', 'source_type', 'source_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_frequent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_account_email', 'contacts', ['account_id', 'email'], unique=True)
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_graph_id'), 'contacts', ['graph_id'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_thread_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('participants_json', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_account_id'), 'email_threads', ['account_id'], unique=False)
    op.create_index('ix_email_threads_graph_id', 'email_threads', ['graph_thread_id'], unique=True)
    op.create_index(op.f('ix_email_threads_graph_thread_id'), 'email_threads', ['graph_thread_id'], unique=False)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('attendees_json', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_account_id'), 'meetings', ['account_id'], unique=False)
    op.create_index('ix_meetings_account_start', 'meetings', ['account_id', 'start_at'], unique=False)
    op.create_index('ix_meetings_graph_id', 'meetings', ['graph_id'], unique=True)
    op.create_index(op.f('ix_meetings_start_at'), 'meetings', ['start_at'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipients_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_account_id'), 'emails', ['account_id'], unique=False)
    op.create_index('ix_emails_account_received', 'emails', ['account_id', 'received_at'], unique=False)
    op.create_index('ix_emails_graph_id', 'emails', ['graph_id'], unique=True)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_email_id', sa.String(length=36), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('expected_reply_by', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REMINDER_SENT', 'DRAFT_PREPARED', 'SENT', 'COMPLETED', 'DISMISSED', name='followupstatus'), nullable=False),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_contact_email'), 'followups', ['contact_email'], unique=False)
    op.create_index('ix_followups_expected_reply', 'followups', ['expected_reply_by'], unique=False)
    op.create_index(op.f('ix_followups_expected_reply_by'), 'followups', ['expected_reply_by'], unique=False)
    op.create_index(op.f('ix_followups_source_email_id'), 'followups', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_followups_user_id'), 'followups', ['user_id'], unique=False)
    op.create_index('ix_followups_user_status', 'followups', ['user_id', 'status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('source_email_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'WAITING_RESPONSE', 'REQUIRES_DECISION', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index(op.f('ix_tasks_deadline_at'), 'tasks', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_source_email_id'), 'tasks', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_user_deadline', 'tasks', ['user_id', 'deadline_at'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_email_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='commitmentstatus'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('related_task_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commitments_due_date', 'commitments', ['due_date'], unique=False)
    op.create_index(op.f('ix_commitments_related_task_id'), 'commitments', ['related_task_id'], unique=False)
    op.create_index(op.f('ix_commitments_source_email_id'), 'commitments', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_index('ix_commitments_user_status', 'commitments', ['user_id', 'status'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_task_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_index('ix_task_deps_task_depends', 'task_dependencies', ['task_id', 'depends_on_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_deps_task_depends', table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_commitments_user_status', table_name='commitments')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_source_email_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_related_task_id'), table_name='commitments')
    op.drop_index('ix_commitments_due_date', table_name='commitments')
    op.drop_table('commitments')
    op.drop_index('ix_tasks_user_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_user_deadline', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_email_id'), table_name='tasks')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_followups_user_status', table_name='followups')
    op.drop_index(op.f('ix_followups_user_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_source_email_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_expected_reply_by'), table_name='followups')
    op.drop_index('ix_followups_expected_reply', table_name='followups')
    op.drop_index(op.f('ix_followups_contact_email'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index('ix_emails_graph_id', table_name='emails')
    op.drop_index('ix_emails_account_received', table_name='emails')
    op.drop_index(op.f('ix_emails_account_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_meetings_start_at'), table_name='meetings')
    op.drop_index('ix_meetings_graph_id', table_name='meetings')
    op.drop_index('ix_meetings_account_start', table_name='meetings')
    op.drop_index(op.f('ix_meetings_account_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_graph_thread_id'), table_name='email_threads')
    op.drop_index('ix_email_threads_graph_id', table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_account_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_contacts_graph_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.drop_index('ix_contacts_account_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_ai_memory_user_source', table_name='ai_memory')
    op.drop_index(op.f('ix_ai_memory_user_id'), table_name='ai_memory')
    op.drop_index(op.f('ix_ai_memory_embedding_id'), table_name='ai_memory')
    op.drop_table('ai_memory')
    op.drop_index('ix_settings_user_key', table_name='settings')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_index('ix_event_logs_type_created', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_correlation_id'), table_name='event_logs')
    op.drop_index('ix_event_logs_correlation', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_embeddings_vector_id'), table_name='embeddings')
    op.drop_index('ix_embeddings_user_vector', table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_user_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_accounts_user_provider', table_name='accounts')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_provider_account_id'), table_name='accounts')
    op.drop_index('ix_accounts_provider_account', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###