"""Add SharePoint models

Revision ID: 56eb2dcf4727
Revises: 3f1d495bf47b
Create Date: 2026-09-29 15:29:03.063456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56eb2dcf4727'
down_revision: Union[str, None] = '3f1d495bf47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharepoint_delta_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_delta_links_account_id'), 'sharepoint_delta_links', ['account_id'], unique=False)
    op.create_index('ix_sp_delta_account_resource', 'sharepoint_delta_links', ['account_id', 'resource_type', 'resource_id'], unique=True)
    op.create_table('sharepoint_sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_sites_account_id'), 'sharepoint_sites', ['account_id'], unique=False)
    op.create_index('ix_sharepoint_sites_graph_id', 'sharepoint_sites', ['graph_id'], unique=True)
    op.create_table('sharepoint_drives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('drive_type', sa.String(length=50), nullable=False),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sharepoint_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_drives_account_id'), 'sharepoint_drives', ['account_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_drives_graph_id'), 'sharepoint_drives', ['graph_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_drives_site_id'), 'sharepoint_drives', ['site_id'], unique=False)
    op.create_table('sharepoint_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_template', sa.String(length=50), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sharepoint_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_lists_account_id'), 'sharepoint_lists', ['account_id'], unique=False)
    op.create_index('ix_sharepoint_lists_graph_id', 'sharepoint_lists', ['graph_id'], unique=True)
    op.create_index(op.f('ix_sharepoint_lists_site_id'), 'sharepoint_lists', ['site_id'], unique=False)
    op.create_table('sharepoint_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('last_modified_by_id', sa.String(length=255), nullable=True),
    sa.Column('last_modified_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at_local', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drive_id'], ['sharepoint_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['sharepoint_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_items_account_id'), 'sharepoint_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_content_hash'), 'sharepoint_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_created_at'), 'sharepoint_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_drive_id'), 'sharepoint_items', ['drive_id'], unique=False)
    op.create_index('ix_sharepoint_items_drive_parent', 'sharepoint_items', ['drive_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_graph_id'), 'sharepoint_items', ['graph_id'], unique=False)
    op.create_index('ix_sharepoint_items_last_modified', 'sharepoint_items', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_last_modified_at'), 'sharepoint_items', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_sharepoint_items_parent_id'), 'sharepoint_items', ['parent_id'], unique=False)
    op.create_table('sharepoint_list_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('list_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['sharepoint_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_list_items_account_id'), 'sharepoint_list_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_list_items_graph_id'), 'sharepoint_list_items', ['graph_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_list_items_last_modified_at'), 'sharepoint_list_items', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_sharepoint_list_items_list_id'), 'sharepoint_list_items', ['list_id'], unique=False)
    op.create_index('ix_sharepoint_list_items_list_modified', 'sharepoint_list_items', ['list_id', 'last_modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sharepoint_list_items_list_modified', table_name='sharepoint_list_items')
    op.drop_index(op.f('ix_sharepoint_list_items_list_id'), table_name='sharepoint_list_items')
    op.drop_index(op.f('ix_sharepoint_list_items_last_modified_at'), table_name='sharepoint_list_items')
    op.drop_index(op.f('ix_sharepoint_list_items_graph_id'), table_name='sharepoint_list_items')
    op.drop_index(op.f('ix_sharepoint_list_items_account_id'), table_name='sharepoint_list_items')
    op.drop_table('sharepoint_list_items')
    op.drop_index(op.f('ix_sharepoint_items_parent_id'), table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_last_modified_at'), table_name='sharepoint_items')
    op.drop_index('ix_sharepoint_items_last_modified', table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_graph_id'), table_name='sharepoint_items')
    op.drop_index('ix_sharepoint_items_drive_parent', table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_drive_id'), table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_created_at'), table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_content_hash'), table_name='sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_items_account_id'), table_name='sharepoint_items')
    op.drop_table('sharepoint_items')
    op.drop_index(op.f('ix_sharepoint_lists_site_id'), table_name='sharepoint_lists')
    op.drop_index('ix_sharepoint_lists_graph_id', table_name='sharepoint_lists')
    op.drop_index(op.f('ix_sharepoint_lists_account_id'), table_name='sharepoint_lists')
    op.drop_table('sharepoint_lists')
    op.drop_index(op.f('ix_sharepoint_drives_site_id'), table_name='sharepoint_drives')
    op.drop_index(op.f('ix_sharepoint_drives_graph_id'), table_name='sharepoint_drives')
    op.drop_index(op.f('ix_sharepoint_drives_account_id'), table_name='sharepoint_drives')
    op.drop_table('sharepoint_drives')
    op.drop_index('ix_sharepoint_sites_graph_id', table_name='sharepoint_sites')
    op.drop_index(op.f('ix_sharepoint_sites_account_id'), table_name='sharepoint_sites')
    op.drop_table('sharepoint_sites')
    op.drop_index('ix_sp_delta_account_resource', table_name='sharepoint_delta_links')
    op.drop_index(op.f('ix_sharepoint_delta_links_account_id'), table_name='sharepoint_delta_links')
    op.drop_table('sharepoint_delta_links')
    # ### end Alembic commands ###