"""Add Teams models and is_processed field

Revision ID: 658cba26ab64
Revises: 464f02899512
Create Date: 2026-09-29 15:17:53.252190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658cba26ab64'
down_revision: Union[str, None] = '464f02899512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_channels_account_id'), 'teams_channels', ['account_id'], unique=False)
    op.create_index(op.f('ix_teams_channels_graph_id'), 'teams_channels', ['graph_id'], unique=False)
    op.create_index('ix_teams_channels_team_graph', 'teams_channels', ['team_id', 'graph_id'], unique=True)
    op.create_index(op.f('ix_teams_channels_team_id'), 'teams_channels', ['team_id'], unique=False)
    op.create_table('teams_chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('chat_type', sa.String(length=50), nullable=False),
    sa.Column('members_json', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_chats_account_id'), 'teams_chats', ['account_id'], unique=False)
    op.create_index('ix_teams_chats_graph_id', 'teams_chats', ['graph_id'], unique=True)
    op.create_index(op.f('ix_teams_chats_last_message_at'), 'teams_chats', ['last_message_at'], unique=False)
    op.create_table('teams_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=False),
    sa.Column('mentions_json', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['teams_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_messages_account_id'), 'teams_messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_teams_messages_chat_id'), 'teams_messages', ['chat_id'], unique=False)
    op.create_index('ix_teams_messages_chat_sent', 'teams_messages', ['chat_id', 'sent_at'], unique=False)
    op.create_index('ix_teams_messages_graph_id', 'teams_messages', ['graph_id'], unique=True)
    op.create_index(op.f('ix_teams_messages_sent_at'), 'teams_messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_messages_sent_at'), table_name='teams_messages')
    op.drop_index('ix_teams_messages_graph_id', table_name='teams_messages')
    op.drop_index('ix_teams_messages_chat_sent', table_name='teams_messages')
    op.drop_index(op.f('ix_teams_messages_chat_id'), table_name='teams_messages')
    op.drop_index(op.f('ix_teams_messages_account_id'), table_name='teams_messages')
    op.drop_table('teams_messages')
    op.drop_index(op.f('ix_teams_chats_last_message_at'), table_name='teams_chats')
    op.drop_index('ix_teams_chats_graph_id', table_name='teams_chats')
    op.drop_index(op.f('ix_teams_chats_account_id'), table_name='teams_chats')
    op.drop_table('teams_chats')
    op.drop_index(op.f('ix_teams_channels_team_id'), table_name='teams_channels')
    op.drop_index('ix_teams_channels_team_graph', table_name='teams_channels')
    op.drop_index(op.f('ix_teams_channels_graph_id'), table_name='teams_channels')
    op.drop_index(op.f('ix_teams_channels_account_id'), table_name='teams_channels')
    op.drop_table('teams_channels')
    # ### end Alembic commands ###